FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install streamlit

EXPOSE 8501

COPY streamlit-app.py streamlit-app.py

ENTRYPOINT [ "streamlit", "run", "streamlit-app.py", "--server.runOnSave=true"]