FROM python:3.10-bullseye

WORKDIR /app


RUN pip install uv
RUN uv pip install --system streamlit

EXPOSE 8501

COPY streamlit-app.py streamlit-app.py

ENTRYPOINT [ "streamlit", "run", "streamlit-app.py", "--server.runOnSave=true"]