services:
  app:
    build: .
    ports:
      - "8501:8501"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    env_file:
      - .env
